// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "./components/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stock App",
  description: "Generated by Aiden",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 전체 앱의 공통 레이아웃 구조 */}
        <div className="flex h-screen w-full bg-slate-50 dark:bg-[#101922] text-slate-900 dark:text-white font-sans overflow-hidden">
          {/* 사이드바 전역 배치 */}
          <Sidebar />

          {/* 페이지별 컨텐츠가 들어가는 곳 */}
          <main className="flex-1 flex flex-col h-full overflow-hidden">
            {children}
          </main>

          {/* 공통 UI (AI 버튼 등) */}
          <button className="fixed bottom-6 right-6 w-14 h-14 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold shadow-2xl hover:scale-110 transition-transform z-50">
            AI
          </button>
        </div>
      </body>
    </html>
  );
}