"""add composite indexes to inventory_transactions

Revision ID: 2b423957f08f
Revises: 
Create Date: 2026-01-31 01:22:20.505090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.types

# revision identifiers, used by Alembic.
revision: str = '2b423957f08f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'id',
               existing_type=sa.UUID(),
               comment='카테고리 고유 식별자',
               existing_nullable=False)
    op.alter_column('categories', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment='카테고리 코드 (짧은 식별자, 예: SK, MU, HC)',
               existing_nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='카테고리 이름 (예: 스킨케어, 메이크업, 헤어케어)',
               existing_nullable=False)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='정렬 순서 (작은 숫자가 먼저 표시됨, UI 표시 순서 제어)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='카테고리 등록일시',
               existing_nullable=False)
    op.drop_constraint('categories_code_key', 'categories', type_='unique')
    op.create_index(op.f('ix_categories_code'), 'categories', ['code'], unique=True)
    op.alter_column('current_stocks', 'product_id',
               existing_type=sa.UUID(),
               comment='제품 ID (복합 PK, FK)',
               existing_nullable=False)
    op.alter_column('current_stocks', 'store_id',
               existing_type=sa.UUID(),
               comment='매장 ID (복합 PK, FK)',
               existing_nullable=False)
    op.alter_column('current_stocks', 'quantity',
               existing_type=sa.INTEGER(),
               comment='현재 재고 수량 (음수 불가, 0 이상)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('current_stocks', 'last_alerted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='마지막 안전재고 알림 발송 시각 (중복 알림 방지용)',
               existing_nullable=True)
    op.alter_column('current_stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='최종 수정일시 (재고 변동 시각)',
               existing_nullable=False)
    op.drop_index('idx_current_stocks_store_id', table_name='current_stocks')
    op.add_column('inventory_transactions', sa.Column('local_id', app.db.types.GUID(), nullable=True, comment='클라이언트 로컬 ID (오프라인 생성 ID)'))
    op.alter_column('inventory_transactions', 'id',
               existing_type=sa.UUID(),
               comment='트랜잭션 고유 식별자',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'product_id',
               existing_type=sa.UUID(),
               comment='제품 ID',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'store_id',
               existing_type=sa.UUID(),
               comment='매장/창고 ID',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='트랜잭션 작성자 ID (MVP 단계에서는 NULL 허용)')
    op.alter_column('inventory_transactions', 'type',
               existing_type=postgresql.ENUM('INBOUND', 'OUTBOUND', 'ADJUST', name='transaction_type'),
               comment='트랜잭션 유형 (INBOUND/OUTBOUND/ADJUST)',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'quantity',
               existing_type=sa.INTEGER(),
               comment='수량 변화 (양수=입고, 음수=출고/조정)',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'reason',
               existing_type=postgresql.ENUM('EXPIRED', 'DAMAGED', 'CORRECTION', 'OTHER', name='adjust_reason'),
               comment='조정 사유 (type=ADJUST일 때 필수)',
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'note',
               existing_type=sa.TEXT(),
               comment='비고 (자유 텍스트)',
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='트랜잭션 발생 일시 (오프라인 시 로컬 시각)',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'synced_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='서버 동기화 완료 일시 (NULL=동기화 대기)',
               existing_nullable=True)
    op.drop_index('idx_inventory_transactions_created_at', table_name='inventory_transactions')
    op.drop_index('idx_inventory_transactions_product_id', table_name='inventory_transactions')
    op.drop_index('idx_inventory_transactions_store_id', table_name='inventory_transactions')
    op.drop_index('idx_inventory_transactions_synced_at', table_name='inventory_transactions', postgresql_where='(synced_at IS NULL)')
    op.create_index('idx_transactions_product_created', 'inventory_transactions', ['product_id', 'created_at'], unique=False)
    op.create_index('idx_transactions_store_created', 'inventory_transactions', ['store_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_created_at'), 'inventory_transactions', ['created_at'], unique=False)
    op.create_unique_constraint(op.f('uq_inventory_transactions_local_id'), 'inventory_transactions', ['local_id'])
    op.alter_column('products', 'id',
               existing_type=sa.UUID(),
               comment='제품 고유 식별자',
               existing_nullable=False)
    op.alter_column('products', 'barcode',
               existing_type=sa.VARCHAR(length=50),
               comment='제품 바코드 (EAN-13 등, 예: 8801234567890)',
               existing_nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='제품 이름 (예: 하이드라 에센스 100ml)',
               existing_nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               comment='카테고리 ID (FK)',
               existing_nullable=False)
    op.alter_column('products', 'safety_stock',
               existing_type=sa.INTEGER(),
               comment='안전재고 수량 (이 값 미만 시 알림 발생)',
               existing_nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment='제품 이미지 URL (S3, CDN 등)',
               existing_nullable=True)
    op.alter_column('products', 'memo',
               existing_type=sa.TEXT(),
               comment='비고 (자유 텍스트, 예: 베스트셀러, 단종 예정)',
               existing_nullable=True)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성화 여부 (False=단종/판매중지 제품)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='제품 등록일시',
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='최종 수정일시',
               existing_nullable=True)
    op.drop_index('idx_products_barcode', table_name='products')
    op.drop_index('idx_products_category_id', table_name='products')
    op.drop_constraint('products_barcode_key', 'products', type_='unique')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.alter_column('stores', 'id',
               existing_type=sa.UUID(),
               comment='매장 고유 식별자',
               existing_nullable=False)
    op.alter_column('stores', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='매장 코드 (사용자 친화적 식별자, 예: SEOUL-01)',
               existing_nullable=False)
    op.alter_column('stores', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='매장 이름 (예: 서울 강남점)',
               existing_nullable=False)
    op.alter_column('stores', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment='매장 주소',
               existing_nullable=True)
    op.alter_column('stores', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='매장 전화번호',
               existing_nullable=True)
    op.alter_column('stores', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성화 여부 (False=비활성화/폐점된 매장)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='매장 등록일시',
               existing_nullable=False)
    op.alter_column('stores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='최종 수정일시',
               existing_nullable=True)
    op.drop_constraint('stores_code_key', 'stores', type_='unique')
    op.create_index(op.f('ix_stores_code'), 'stores', ['code'], unique=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='사용자 고유 식별자',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='로그인 이메일 주소',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt 해싱된 비밀번호 (평문 저장 절대 금지)',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('WORKER', 'ADMIN', name='user_role'),
               comment='사용자 역할 (WORKER 또는 ADMIN)',
               existing_nullable=False,
               existing_server_default=sa.text("'WORKER'::user_role"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성화 여부 (False=비활성화/삭제된 사용자)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='가입일시',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='최종 수정일시',
               existing_nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='최종 수정일시',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='가입일시',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='활성화 여부 (False=비활성화/삭제된 사용자)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('WORKER', 'ADMIN', name='user_role'),
               comment=None,
               existing_comment='사용자 역할 (WORKER 또는 ADMIN)',
               existing_nullable=False,
               existing_server_default=sa.text("'WORKER'::user_role"))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='사용자 이름',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt 해싱된 비밀번호 (평문 저장 절대 금지)',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='로그인 이메일 주소',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='사용자 고유 식별자',
               existing_nullable=False)
    op.drop_index(op.f('ix_stores_code'), table_name='stores')
    op.create_unique_constraint('stores_code_key', 'stores', ['code'])
    op.alter_column('stores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='최종 수정일시',
               existing_nullable=True)
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='매장 등록일시',
               existing_nullable=False)
    op.alter_column('stores', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='활성화 여부 (False=비활성화/폐점된 매장)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('stores', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='매장 전화번호',
               existing_nullable=True)
    op.alter_column('stores', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='매장 주소',
               existing_nullable=True)
    op.alter_column('stores', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='매장 이름 (예: 서울 강남점)',
               existing_nullable=False)
    op.alter_column('stores', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='매장 코드 (사용자 친화적 식별자, 예: SEOUL-01)',
               existing_nullable=False)
    op.alter_column('stores', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='매장 고유 식별자',
               existing_nullable=False)
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_unique_constraint('products_barcode_key', 'products', ['barcode'])
    op.create_index('idx_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('idx_products_barcode', 'products', ['barcode'], unique=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='최종 수정일시',
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='제품 등록일시',
               existing_nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='활성화 여부 (False=단종/판매중지 제품)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'memo',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='비고 (자유 텍스트, 예: 베스트셀러, 단종 예정)',
               existing_nullable=True)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='제품 이미지 URL (S3, CDN 등)',
               existing_nullable=True)
    op.alter_column('products', 'safety_stock',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='안전재고 수량 (이 값 미만 시 알림 발생)',
               existing_nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='카테고리 ID (FK)',
               existing_nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='제품 이름 (예: 하이드라 에센스 100ml)',
               existing_nullable=False)
    op.alter_column('products', 'barcode',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='제품 바코드 (EAN-13 등, 예: 8801234567890)',
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='제품 고유 식별자',
               existing_nullable=False)
    op.drop_constraint(op.f('uq_inventory_transactions_local_id'), 'inventory_transactions', type_='unique')
    op.drop_index(op.f('ix_inventory_transactions_created_at'), table_name='inventory_transactions')
    op.drop_index('idx_transactions_store_created', table_name='inventory_transactions')
    op.drop_index('idx_transactions_product_created', table_name='inventory_transactions')
    op.create_index('idx_inventory_transactions_synced_at', 'inventory_transactions', ['synced_at'], unique=False, postgresql_where='(synced_at IS NULL)')
    op.create_index('idx_inventory_transactions_store_id', 'inventory_transactions', ['store_id'], unique=False)
    op.create_index('idx_inventory_transactions_product_id', 'inventory_transactions', ['product_id'], unique=False)
    op.create_index('idx_inventory_transactions_created_at', 'inventory_transactions', [sa.text('created_at DESC')], unique=False)
    op.alter_column('inventory_transactions', 'synced_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='서버 동기화 완료 일시 (NULL=동기화 대기)',
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='트랜잭션 발생 일시 (오프라인 시 로컬 시각)',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='비고 (자유 텍스트)',
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'reason',
               existing_type=postgresql.ENUM('EXPIRED', 'DAMAGED', 'CORRECTION', 'OTHER', name='adjust_reason'),
               comment=None,
               existing_comment='조정 사유 (type=ADJUST일 때 필수)',
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='수량 변화 (양수=입고, 음수=출고/조정)',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'type',
               existing_type=postgresql.ENUM('INBOUND', 'OUTBOUND', 'ADJUST', name='transaction_type'),
               comment=None,
               existing_comment='트랜잭션 유형 (INBOUND/OUTBOUND/ADJUST)',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='트랜잭션 작성자 ID (MVP 단계에서는 NULL 허용)')
    op.alter_column('inventory_transactions', 'store_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='매장/창고 ID',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='제품 ID',
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='트랜잭션 고유 식별자',
               existing_nullable=False)
    op.drop_column('inventory_transactions', 'local_id')
    op.create_index('idx_current_stocks_store_id', 'current_stocks', ['store_id'], unique=False)
    op.alter_column('current_stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='최종 수정일시 (재고 변동 시각)',
               existing_nullable=False)
    op.alter_column('current_stocks', 'last_alerted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='마지막 안전재고 알림 발송 시각 (중복 알림 방지용)',
               existing_nullable=True)
    op.alter_column('current_stocks', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='현재 재고 수량 (음수 불가, 0 이상)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('current_stocks', 'store_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='매장 ID (복합 PK, FK)',
               existing_nullable=False)
    op.alter_column('current_stocks', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='제품 ID (복합 PK, FK)',
               existing_nullable=False)
    op.drop_index(op.f('ix_categories_code'), table_name='categories')
    op.create_unique_constraint('categories_code_key', 'categories', ['code'])
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='카테고리 등록일시',
               existing_nullable=False)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='정렬 순서 (작은 숫자가 먼저 표시됨, UI 표시 순서 제어)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='카테고리 이름 (예: 스킨케어, 메이크업, 헤어케어)',
               existing_nullable=False)
    op.alter_column('categories', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='카테고리 코드 (짧은 식별자, 예: SK, MU, HC)',
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='카테고리 고유 식별자',
               existing_nullable=False)
    # ### end Alembic commands ###
